// Ficha de cada dispositivo en templates.blakadder.com (referencia Tasmota).
//   r = URL de la ficha completa   |   i = URL de la foto del dispositivo
// Clave: "Categoría|Modelo" EXACTAMENTE como en devices.js. Generado automáticamente.
const BLAKADDER_REF = {
  "Athom|Athom 1 Gang No Neutral": { r: "https://templates.blakadder.com/athom_SW111EU.html", i: "https://templates.blakadder.com/assets/device_images/athom_SW111EU.webp" },
  "Athom|Athom 1 Gang No Neutral Touch": { r: "https://templates.blakadder.com/athom_SW33-TAS-1US.html", i: "https://templates.blakadder.com/assets/device_images/athom_SW33-TAS-1US.webp" },
  "Athom|Athom 16A AU V3 Plug": { r: "https://templates.blakadder.com/athom_PG05V3-AU10A-TAS.html", i: "https://templates.blakadder.com/assets/device_images/athom_PG05V2-AU16A-TAS.webp" },
  "Athom|Athom 16A UK V3 Plug": { r: "https://templates.blakadder.com/athom_PG04V3-UK16A-TAS.html", i: "https://templates.blakadder.com/assets/device_images/athom_PG04V2-UK16A-TAS.webp" },
  "Athom|Athom 16A UK Wall Outlet SK03": { r: "https://templates.blakadder.com/athom_SK03-TAS.html", i: "https://templates.blakadder.com/assets/device_images/athom_SK03-TAS.webp" },
  "Athom|Athom 16A US Plug PG03-US16A": { r: "https://templates.blakadder.com/athom_PG03-US16A.html", i: "https://templates.blakadder.com/assets/device_images/athom_PG03-US16A.webp" },
  "Athom|Athom 16A US V3 Plug": { r: "https://templates.blakadder.com/athom_PG03V3-US16A-TAS.html", i: "https://templates.blakadder.com/assets/device_images/athom_PG03V2-US16A-TAS.webp" },
  "Athom|Athom 2 Gang No Neutral": { r: "https://templates.blakadder.com/athom_SW112EU.html", i: "https://templates.blakadder.com/assets/device_images/athom_SW112EU.webp" },
  "Athom|Athom 2 Gang No Neutral Touch": { r: "https://templates.blakadder.com/athom_SW33-TAS-2US.html", i: "https://templates.blakadder.com/assets/device_images/athom_SW33-TAS-2US.webp" },
  "Athom|Athom 3 Gang Key": { r: "https://templates.blakadder.com/athom_SW01-TAS-3EU.html", i: "https://templates.blakadder.com/assets/device_images/athom_SW01-TAS-3EU.webp" },
  "Athom|Athom 3 Gang No Neutral Touch": { r: "https://templates.blakadder.com/athom_SW33-TAS-3US.html", i: "https://templates.blakadder.com/assets/device_images/athom_SW33-TAS-3US.webp" },
  "Athom|Athom 4 Gang No Neutral Touch": { r: "https://templates.blakadder.com/athom_SW33-TAS-4US.html", i: "https://templates.blakadder.com/assets/device_images/athom_SW33-TAS-4US.webp" },
  "Athom|Athom 4Ch Inching/Self-locking 10A": { r: "https://templates.blakadder.com/athom_R04.html", i: "https://templates.blakadder.com/assets/device_images/athom_R04.webp" },
  "Athom|Athom 4Ch Inching/Self-locking 30A": { r: "https://templates.blakadder.com/athom_R04-30A.html", i: "https://templates.blakadder.com/assets/device_images/athom_R04-30A.webp" },
  "Athom|Athom 5-24V 16A RGBW LED Controller LS5P": { r: "https://templates.blakadder.com/athom_LS5P-TAS.html", i: "https://templates.blakadder.com/assets/device_images/athom_LS5P-TAS.webp" },
  "Athom|Athom 7W 600lm RGBCCT LB017W": { r: "https://templates.blakadder.com/athom_LB017W.html", i: "https://templates.blakadder.com/assets/device_images/athom_LB017W.webp" },
  "Athom|Athom Curtain Module KM01": { r: "https://templates.blakadder.com/athom_KM01-TAS.html", i: "https://templates.blakadder.com/assets/device_images/athom_KM01-TAS.webp" },
  "Athom|Athom EM2 Energy Meter": { r: "https://templates.blakadder.com/athom_EM2.html", i: "https://templates.blakadder.com/assets/device_images/athom_em2.webp" },
  "Athom|Athom EM6 Energy Meter": { r: "https://templates.blakadder.com/athom_EM6.html", i: "https://templates.blakadder.com/assets/device_images/athom_em6.webp" },
  "Athom|Athom ESP32 Ethernet Zigbee Gateway": { r: "https://templates.blakadder.com/athom_ZG01.html", i: "https://templates.blakadder.com/assets/device_images/athom__ZG01.webp" },
  "Athom|Athom ESP32C3 12W Bulb": { r: "https://templates.blakadder.com/athom_LB01-12W-E27.html", i: "https://templates.blakadder.com/assets/device_images/athom_LB01-12W-E27.webp" },
  "Athom|Athom EU Dimmer SD01": { r: "https://templates.blakadder.com/athom_SD01-EU-TAS.html", i: "https://templates.blakadder.com/assets/device_images/athom_SD01-EU-TAS.webp" },
  "Athom|Athom Human Presence Sensor": { r: "https://templates.blakadder.com/athom_PS01.html", i: "https://templates.blakadder.com/assets/device_images/athom_PS01.webp" },
  "Athom|Athom IR Controller AR01": { r: "https://templates.blakadder.com/athom_AR01.html", i: "https://templates.blakadder.com/assets/device_images/athom_AR01.webp" },
  "Athom|Athom Plug V3": { r: "https://templates.blakadder.com/athom_PG01V3-EU16A.html", i: "https://templates.blakadder.com/assets/device_images/athom_PG01V2-EU16A.webp" },
  "Athom|Athom RGB LED Controller LS5050C": { r: "https://templates.blakadder.com/athom_LS5050C-TAS.html", i: "https://templates.blakadder.com/assets/device_images/athom_LS5050C-TAS.webp" },
  "Athom|Athom US Key Switch 1 Gang": { r: "https://templates.blakadder.com/athom_SW13.html", i: "https://templates.blakadder.com/assets/device_images/athom_SW13.webp" },
  "Athom|Athom Wall Outlet SK01": { r: "https://templates.blakadder.com/athom_SK01-TAS.html", i: "https://templates.blakadder.com/assets/device_images/athom_SK01-TAS.webp" },
  "Shelly|Shelly 1": { r: "https://templates.blakadder.com/shelly_1.html", i: "https://templates.blakadder.com/assets/device_images/shelly_1.webp" },
  "Shelly|Shelly 1L No Neutral": { r: "https://templates.blakadder.com/shelly_1L.html", i: "https://templates.blakadder.com/assets/device_images/shelly_1L.webp" },
  "Shelly|Shelly 1PM": { r: "https://templates.blakadder.com/shelly_1PM.html", i: "https://templates.blakadder.com/assets/device_images/shelly_1PM.webp" },
  "Shelly|Shelly 1PM Gen4": { r: "https://templates.blakadder.com/shelly_1PM_Gen4.html", i: "https://templates.blakadder.com/assets/device_images/shelly_1PM_Gen4.webp" },
  "Shelly|Shelly 2": { r: "https://templates.blakadder.com/shelly_2.html", i: "https://templates.blakadder.com/assets/device_images/shelly_2.webp" },
  "Shelly|Shelly 2.5": { r: "https://templates.blakadder.com/shelly_25.html", i: "https://templates.blakadder.com/assets/device_images/shelly_25.webp" },
  "Shelly|Shelly 2PM Gen4": { r: "https://templates.blakadder.com/shelly_2PM_gen4.html", i: "https://templates.blakadder.com/assets/device_images/shelly_2PM_gen4.webp" },
  "Shelly|Shelly 3EM": { r: "https://templates.blakadder.com/shelly_3EM.html", i: "https://templates.blakadder.com/assets/device_images/shelly_3EM.webp" },
  "Shelly|Shelly Add-on Temperature Sensor": { r: "https://templates.blakadder.com/shelly_temperature_sensor.html", i: "https://templates.blakadder.com/assets/device_images/shelly_temperature_sensor.webp" },
  "Shelly|Shelly Dimmer": { r: "https://templates.blakadder.com/shelly_Dimmer.html", i: "https://templates.blakadder.com/assets/device_images/shelly_Dimmer.webp" },
  "Shelly|Shelly Dimmer 0/1-10V PM Gen3": { r: "https://templates.blakadder.com/shelly_Dimmer_Gen3.html", i: "https://templates.blakadder.com/assets/device_images/shelly_Dimmer_Gen3.webp" },
  "Shelly|Shelly Dimmer 2": { r: "https://templates.blakadder.com/shelly_Dimmer_2.html", i: "https://templates.blakadder.com/assets/device_images/shelly_Dimmer_2.webp" },
  "Shelly|Shelly Duo": { r: "https://templates.blakadder.com/shelly_DUO.html", i: "https://templates.blakadder.com/assets/device_images/shelly_DUO.webp" },
  "Shelly|Shelly Duo RGBW 9W": { r: "https://templates.blakadder.com/shelly_DUO_RGBW.html", i: "https://templates.blakadder.com/assets/device_images/shelly_DUO_RGBW.webp" },
  "Shelly|Shelly EM": { r: "https://templates.blakadder.com/shelly_EM.html", i: "https://templates.blakadder.com/assets/device_images/shelly_EM.webp" },
  "Shelly|Shelly Plug": { r: "https://templates.blakadder.com/shelly_plug.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plug.webp" },
  "Shelly|Shelly Plug S": { r: "https://templates.blakadder.com/shelly_plug_S.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plug_S.webp" },
  "Shelly|Shelly Plug US": { r: "https://templates.blakadder.com/shelly_plug_US.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plug_US.webp" },
  "Shelly|Shelly Plus 0-10V Dimmer": { r: "https://templates.blakadder.com/shelly_plus_0-10v_dimmer.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plus_0-10v_dimmer.webp" },
  "Shelly|Shelly Plus 1": { r: "https://templates.blakadder.com/shelly_plus_1.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plus_1.webp" },
  "Shelly|Shelly Plus 1 Mini": { r: "https://templates.blakadder.com/shelly_plus_1_mini.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plus_1_mini.webp" },
  "Shelly|Shelly Plus 1PM": { r: "https://templates.blakadder.com/shelly_plus_1PM.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plus_1PM.webp" },
  "Shelly|Shelly Plus 1PM Mini": { r: "https://templates.blakadder.com/shelly_plus_1pm_mini.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plus_1pm_mini.webp" },
  "Shelly|Shelly Plus 2PM": { r: "https://templates.blakadder.com/shelly_plus_2PM.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plus_2PM.webp" },
  "Shelly|Shelly Plus Add-On Temperature Sensor": { r: "https://templates.blakadder.com/shelly_plus_add-on.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plus_add-on.webp" },
  "Shelly|Shelly Plus PM Mini": { r: "https://templates.blakadder.com/shelly_plus_pm_mini.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plus_pm_mini.webp" },
  "Shelly|Shelly Plus Plug S": { r: "https://templates.blakadder.com/shelly_plus_plug_S.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plus_plug_S.webp" },
  "Shelly|Shelly Plus Plug UK": { r: "https://templates.blakadder.com/shelly_plus_plug_uk.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plus_plug_uk.webp" },
  "Shelly|Shelly Plus i4": { r: "https://templates.blakadder.com/shelly_plus_i4.html", i: "https://templates.blakadder.com/assets/device_images/shelly_plus_i4.webp" },
  "Shelly|Shelly Pro 1": { r: "https://templates.blakadder.com/shelly_pro_1.html", i: "https://templates.blakadder.com/assets/device_images/shelly_pro_1.webp" },
  "Shelly|Shelly Pro 1PM": { r: "https://templates.blakadder.com/shelly_pro_1pm.html", i: "https://templates.blakadder.com/assets/device_images/shelly_pro_1pm.webp" },
  "Shelly|Shelly Pro 2": { r: "https://templates.blakadder.com/shelly_pro_2.html", i: "https://templates.blakadder.com/assets/device_images/shelly_pro_2.webp" },
  "Shelly|Shelly Pro 2PM": { r: "https://templates.blakadder.com/shelly_pro_2pm.html", i: "https://templates.blakadder.com/assets/device_images/shelly_pro_2pm.webp" },
  "Shelly|Shelly Pro 3": { r: "https://templates.blakadder.com/shelly_pro_3.html", i: "https://templates.blakadder.com/assets/device_images/shelly_pro_3.webp" },
  "Shelly|Shelly RGBW2": { r: "https://templates.blakadder.com/shelly_RGBW2.html", i: "https://templates.blakadder.com/assets/device_images/shelly_RGBW2.webp" },
  "Shelly|Shelly i3": { r: "https://templates.blakadder.com/shelly_i3.html", i: "https://templates.blakadder.com/assets/device_images/shelly_i3.webp" },
  "Sonoff|Sonoff 1 Channel Inching/Self-Locking": { r: "https://templates.blakadder.com/sonoff_1channel.html", i: "https://user-images.githubusercontent.com/5904370/57887139-173a3f00-782f-11e9-8bcc-b0a41451bb10.png" },
  "Sonoff|Sonoff 4CH (R2)": { r: "https://templates.blakadder.com/sonoff_4CH.html", i: "https://user-images.githubusercontent.com/5904370/57882765-c4f42080-7824-11e9-93c9-fafaf0299dd0.png" },
  "Sonoff|Sonoff 4CH Pro (R2)": { r: "https://templates.blakadder.com/sonoff_4CH_Pro.html", i: "https://user-images.githubusercontent.com/5904370/57883997-f91d1080-7827-11e9-96dd-f7a0a6df0edc.png" },
  "Sonoff|Sonoff 4CHPROR3": { r: "https://templates.blakadder.com/sonoff_4CHPROR3.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_4CHPROR3.webp" },
  "Sonoff|Sonoff 4CHR3": { r: "https://templates.blakadder.com/sonoff_4CHR3.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_4CHR3.webp" },
  "Sonoff|Sonoff B1 (R2) RGBCCT": { r: "https://templates.blakadder.com/sonoff_B1.html", i: "https://user-images.githubusercontent.com/5904370/57892486-5f615d80-783f-11e9-8273-1b08e163047a.png" },
  "Sonoff|Sonoff BASICR4": { r: "https://templates.blakadder.com/sonoff_BASICR4.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_BASICR4.webp" },
  "Sonoff|Sonoff Basic": { r: "https://templates.blakadder.com/sonoff_basic.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_basic.webp" },
  "Sonoff|Sonoff Basic R2": { r: "https://templates.blakadder.com/sonoff_BASICR2.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_BASICR2.webp" },
  "Sonoff|Sonoff Basic R3": { r: "https://templates.blakadder.com/sonoff_basic_R3.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_BASICR3.webp" },
  "Sonoff|Sonoff D1": { r: "https://templates.blakadder.com/sonoff_D1.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_D1.webp" },
  "Sonoff|Sonoff Dual": { r: "https://templates.blakadder.com/sonoff_dual.html", i: "https://user-images.githubusercontent.com/5904370/57879170-121fc480-781c-11e9-8bed-7ba8ad73f579.png" },
  "Sonoff|Sonoff Dual R2": { r: "https://templates.blakadder.com/sonoff_dual_R2.html", i: "https://user-images.githubusercontent.com/5904370/57879170-121fc480-781c-11e9-8bed-7ba8ad73f579.png" },
  "Sonoff|Sonoff Dual R3": { r: "https://templates.blakadder.com/sonoff_DUALR3.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_DUALR3.webp" },
  "Sonoff|Sonoff Dual R3 Lite": { r: "https://templates.blakadder.com/sonoff_DUALR3L.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_DUALR3L.webp" },
  "Sonoff|Sonoff Dual R3 v2": { r: "https://templates.blakadder.com/sonoff_DUALR3_v2.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_DUALR3.webp" },
  "Sonoff|Sonoff IW100": { r: "https://templates.blakadder.com/sonoff_IW100.html", i: "https://user-images.githubusercontent.com/5904370/73012669-16729780-3e17-11ea-8b4c-c0ace8c9811c.png" },
  "Sonoff|Sonoff IW101": { r: "https://templates.blakadder.com/sonoff_IW101.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_IW101.webp" },
  "Sonoff|Sonoff L1 LED Strip": { r: "https://templates.blakadder.com/sonoff_L1.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_L1.webp" },
  "Sonoff|Sonoff L1 Lite RGB LED Strip": { r: "https://templates.blakadder.com/sonoff_L1_Lite.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_L1_Lite.webp" },
  "Sonoff|Sonoff Light BN-SZ01": { r: "https://templates.blakadder.com/sonoff_BN-SZ01.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_BN-SZ01.webp" },
  "Sonoff|Sonoff Mini": { r: "https://templates.blakadder.com/sonoff_MINIR2.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_MINIR2.webp" },
  "Sonoff|Sonoff Mini Extreme": { r: "https://templates.blakadder.com/sonoff_MINIR4.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_MINIR4.webp" },
  "Sonoff|Sonoff Mini R2": { r: "https://templates.blakadder.com/sonoff_MINIR2.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_MINIR2.webp" },
  "Sonoff|Sonoff NSPanel": { r: "https://templates.blakadder.com/sonoff_NSPanel.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_NSPanel.webp" },
  "Sonoff|Sonoff POW": { r: "https://templates.blakadder.com/sonoff_Pow.html", i: "https://user-images.githubusercontent.com/5904370/57881237-139fbb80-7821-11e9-8c1b-e375f6d0c0a3.png" },
  "Sonoff|Sonoff POW Elite 16A": { r: "https://templates.blakadder.com/sonoff_POWR316D.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_POWR316D.webp" },
  "Sonoff|Sonoff POW Elite 20A": { r: "https://templates.blakadder.com/sonoff_POWR320D.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_POWR320D.webp" },
  "Sonoff|Sonoff POW Origin 16A": { r: "https://templates.blakadder.com/sonoff_POWR316.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_POWR316.webp" },
  "Sonoff|Sonoff POW R2": { r: "https://templates.blakadder.com/sonoff_Pow_R2.html", i: "https://user-images.githubusercontent.com/5904370/57882172-65494580-7823-11e9-9202-cac2dccd18b2.png" },
  "Sonoff|Sonoff POW R3 25A 5500W": { r: "https://templates.blakadder.com/sonoff_POWR3.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_POWR3.webp" },
  "Sonoff|Sonoff RE5V1C": { r: "https://templates.blakadder.com/sonoff_RE5V1C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_RE5V1C.webp" },
  "Sonoff|Sonoff RF": { r: "https://templates.blakadder.com/sonoff_RF.html", i: "https://user-images.githubusercontent.com/5904370/57876764-6fb11280-7816-11e9-86c2-9b26626dfe64.png" },
  "Sonoff|Sonoff RF Bridge 433": { r: "https://templates.blakadder.com/sonoff_RF_bridge.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_RF_bridge.webp" },
  "Sonoff|Sonoff S20": { r: "https://templates.blakadder.com/sonoff_S20.html", i: "https://user-images.githubusercontent.com/5904370/57884318-a55ef700-7828-11e9-8cb5-52d9fb54d9fa.png" },
  "Sonoff|Sonoff S22 TH": { r: "https://templates.blakadder.com/sonoff_s22.html", i: "https://www.dhresource.com/webp/m/0x0s/f2-albu-g6-M00-F2-AD-rBVaSFtyKPyAA7NgAAC1azypYqY471.jpg/sonoff-s22-10a-2200w-samrt-plug-wireless.jpg" },
  "Sonoff|Sonoff S26": { r: "https://templates.blakadder.com/sonoff_S26.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_S26.webp" },
  "Sonoff|Sonoff S26 R2": { r: "https://templates.blakadder.com/sonoff_S26R2.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_S26.webp" },
  "Sonoff|Sonoff S31": { r: "https://templates.blakadder.com/sonoff_S31.html", i: "https://user-images.githubusercontent.com/5904370/57948059-f0d4dc00-78e0-11e9-85df-a23c5af638a3.png" },
  "Sonoff|Sonoff S31 Lite": { r: "https://templates.blakadder.com/sonoff_S31-lite.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_S31-lite.webp" },
  "Sonoff|Sonoff S55": { r: "https://templates.blakadder.com/sonoff_S55.html", i: "https://user-images.githubusercontent.com/5904370/61628399-7890eb00-ac82-11e9-9742-3e837ee9f09b.png" },
  "Sonoff|Sonoff SC Environment Sensor": { r: "https://templates.blakadder.com/sonoff_SC.html", i: "https://user-images.githubusercontent.com/5904370/57957790-da894900-78fd-11e9-92c6-7f32fd9d4a59.png" },
  "Sonoff|Sonoff SV": { r: "https://templates.blakadder.com/sonoff_SV.html", i: "https://user-images.githubusercontent.com/5904370/57877355-eef31600-7817-11e9-9812-393f47558adc.png" },
  "Sonoff|Sonoff SwitchMan M5-1C": { r: "https://templates.blakadder.com/sonoff_SwitchMan_M5-1C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_SwitchMan_M5-1C.webp" },
  "Sonoff|Sonoff SwitchMan M5-2C": { r: "https://templates.blakadder.com/sonoff_SwitchMan_M5-2C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_SwitchMan_M5-2C.webp" },
  "Sonoff|Sonoff SwitchMan M5-3C": { r: "https://templates.blakadder.com/sonoff_SwitchMan_M5-3C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_SwitchMan_M5-3C.webp" },
  "Sonoff|Sonoff T1 EU 1 Gang": { r: "https://templates.blakadder.com/sonoff_T1_eu_1.html", i: "https://user-images.githubusercontent.com/5904370/57943003-34c0e480-78d3-11e9-9c94-a83588ace163.png" },
  "Sonoff|Sonoff T1 EU 2 Gang": { r: "https://templates.blakadder.com/sonoff_T1_eu_2.html", i: "https://user-images.githubusercontent.com/5904370/57942984-2c68a980-78d3-11e9-9781-dc9170916d86.png" },
  "Sonoff|Sonoff T1 UK 1 Gang": { r: "https://templates.blakadder.com/sonoff_T1_uk_1.html", i: "https://user-images.githubusercontent.com/5904370/57943737-1c51c980-78d5-11e9-9795-5f3492b08498.png" },
  "Sonoff|Sonoff T1 UK 2 Gang": { r: "https://templates.blakadder.com/sonoff_T1_uk_2.html", i: "https://user-images.githubusercontent.com/5904370/57893156-22e33100-7842-11e9-8749-81db74dac23f.png" },
  "Sonoff|Sonoff T1 UK 3 Gang": { r: "https://templates.blakadder.com/sonoff_T1_uk_3.html", i: "https://user-images.githubusercontent.com/5904370/57893269-984f0180-7842-11e9-910d-71763c3cf6bd.png" },
  "Sonoff|Sonoff T1 US 1 Gang": { r: "https://templates.blakadder.com/sonoff_T1_us_1.html", i: "https://user-images.githubusercontent.com/5904370/57944870-a0f21700-78d8-11e9-8937-63ba1dfd6583.png" },
  "Sonoff|Sonoff T1 US 2 Gang": { r: "https://templates.blakadder.com/sonoff_T1_us_2.html", i: "https://user-images.githubusercontent.com/5904370/57944942-cc750180-78d8-11e9-8267-e960fbe74d0a.png" },
  "Sonoff|Sonoff T1 US 3 Gang": { r: "https://templates.blakadder.com/sonoff_T1_us_3.html", i: "https://user-images.githubusercontent.com/5904370/57944986-ee6e8400-78d8-11e9-99db-49d336c68084.png" },
  "Sonoff|Sonoff TH Elite 16A": { r: "https://templates.blakadder.com/sonoff_THR316D.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_THR316D.webp" },
  "Sonoff|Sonoff TH Elite 20A": { r: "https://templates.blakadder.com/sonoff_THR320D.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_THR320D.webp" },
  "Sonoff|Sonoff TH Origin 16A": { r: "https://templates.blakadder.com/sonoff_THR316.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_THR316.webp" },
  "Sonoff|Sonoff TH Origin 20A": { r: "https://templates.blakadder.com/sonoff_THR320.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_THR320.webp" },
  "Sonoff|Sonoff TH10/TH16": { r: "https://templates.blakadder.com/sonoff_TH.html", i: "https://user-images.githubusercontent.com/5904370/57877996-5e1d3a00-7819-11e9-9008-f183f321d45a.png" },
  "Sonoff|Sonoff TX T0 EU 1 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T0EU1C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T0EU1C.webp" },
  "Sonoff|Sonoff TX T0 EU 2 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T0EU2C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T0EU2C.webp" },
  "Sonoff|Sonoff TX T0 US 3 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T0US3C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T0US3C.webp" },
  "Sonoff|Sonoff TX T1 EU 1 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T1EU1C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T1EU1C.webp" },
  "Sonoff|Sonoff TX T1 EU 2 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T1EU2C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T1EU2C.webp" },
  "Sonoff|Sonoff TX T2 EU 1 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T2EU1C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T2EU1C.webp" },
  "Sonoff|Sonoff TX T2 EU 2 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T2EU2C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T2EU2C.webp" },
  "Sonoff|Sonoff TX T2 UK 2 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T2UK2C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T2UK2C.webp" },
  "Sonoff|Sonoff TX T3 EU 1 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T3EU1C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T3EU1C.webp" },
  "Sonoff|Sonoff TX T3 EU 2 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T3EU2C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T3EU2C.webp" },
  "Sonoff|Sonoff TX T3 EU 3 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T3EU3C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T3EU3C.webp" },
  "Sonoff|Sonoff TX T3 US 3 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T3US3C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T3US3C.webp" },
  "Sonoff|Sonoff TX T4 EU No Neutral 1 Gang": { r: "https://templates.blakadder.com/sonoff_TX-T4EU1C.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_TX-T4EU1C.webp" },
  "Sonoff|Sonoff TX Ultimate 1 Gang": { r: "https://templates.blakadder.com/sonoff_T5-1C-86.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_T5-1C-86.webp" },
  "Sonoff|Sonoff TX Ultimate 2 Gang": { r: "https://templates.blakadder.com/sonoff_T5-2C-86.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_T5-2C-86.webp" },
  "Sonoff|Sonoff TX Ultimate 3 Gang": { r: "https://templates.blakadder.com/sonoff_T5-3C-86.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_T5-3C-86.webp" },
  "Sonoff|Sonoff TX Ultimate 4 Gang": { r: "https://templates.blakadder.com/sonoff_T5-4C-86.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_T5-4C-86.webp" },
  "Sonoff|Sonoff TX Ultimate US 1 Gang": { r: "https://templates.blakadder.com/sonoff_T5-1C-120.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_T5-1C-120.webp" },
  "Sonoff|Sonoff TX Ultimate US 2 Gang": { r: "https://templates.blakadder.com/sonoff_T5-2C-120.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_T5-2C-120.webp" },
  "Sonoff|Sonoff TX Ultimate US 3 Gang": { r: "https://templates.blakadder.com/sonoff_T5-3C-120.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_T5-3C-120.webp" },
  "Sonoff|Sonoff TX Ultimate US 4 Gang": { r: "https://templates.blakadder.com/sonoff_T5-4C-120.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_T5-4C-120.webp" },
  "Sonoff|Sonoff Touch EU": { r: "https://templates.blakadder.com/sonoff_touch_eu.html", i: "https://user-images.githubusercontent.com/5904370/57885431-36cf6880-782b-11e9-9361-f4fa9f60fd80.png" },
  "Sonoff|Sonoff Touch US": { r: "https://templates.blakadder.com/sonoff_touch_us.html", i: "https://user-images.githubusercontent.com/5904370/57885987-84000a00-782c-11e9-90e5-33706c197497.png" },
  "Sonoff|Sonoff ZBBridge": { r: "https://templates.blakadder.com/sonoff_ZBBridge.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_ZBBridge.webp" },
  "Sonoff|Sonoff ZBBridge Pro": { r: "https://templates.blakadder.com/sonoff_ZBBridge-P.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_ZBBridge-P.webp" },
  "Sonoff|Sonoff iFan02": { r: "https://templates.blakadder.com/sonoff_ifan02.html", i: "https://user-images.githubusercontent.com/5904370/57948708-a6545f00-78e2-11e9-9d04-05f31ff77a72.png" },
  "Sonoff|Sonoff iFan03": { r: "https://templates.blakadder.com/sonoff_ifan03.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_iFan03.webp" },
  "Sonoff|Sonoff iFan04-H": { r: "https://templates.blakadder.com/sonoff_iFan04-H.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_iFan04-H.webp" },
  "Sonoff|Sonoff iFan04-L": { r: "https://templates.blakadder.com/sonoff_iFan04-L.html", i: "https://templates.blakadder.com/assets/device_images/sonoff_iFan04-L.webp" },
  "Tuya|AOFO 4AC+4USB Tuya Power Strip C733": { r: "https://templates.blakadder.com/aofo_4AC+4USB_tuya.html", i: "https://images-na.ssl-images-amazon.com/images/I/816DuO0a4WL._SL1500_.jpg" },
  "Tuya|ESP32-C2 Tuya CBU (ESP8684)": { r: "https://templates.blakadder.com/ESP8684-WROOM-06C.html", i: "https://templates.blakadder.com/assets/device_images/ESP8684-WROOM-06C.webp" },
  "Tuya|ESP32-C3 Tuya CBU (ESP8685)": { r: "https://templates.blakadder.com/ESP8685-WROOM-06.html", i: "https://templates.blakadder.com/assets/device_images/ESP8685-WROOM-06.webp" },
  "Tuya|Gosund Wall Outlet WO1 (Tuya)": { r: "https://templates.blakadder.com/gosund_WO1_tuya_convert_date_bump.html", i: "https://templates.blakadder.com/assets/device_images/gosund_WO1.webp" },
  "Tuya|TOVA Dual Plug TO-PLUG-DUAL (Tuya)": { r: "https://templates.blakadder.com/tova_TO-PLUG-DUAL_tuya_convert_note.html", i: "https://templates.blakadder.com/assets/device_images/tova_TO-PLUG-DUAL.webp" },
  "Tuya|Tuya 1 Gang No Neutral": { r: "https://templates.blakadder.com/tuya_DS-1081HL.html", i: "https://templates.blakadder.com/assets/device_images/tuya_DS-1081HL.webp" },
  "Tuya|Tuya 16A Nightlight": { r: "https://templates.blakadder.com/tuya_nightlight_plug.html", i: "https://templates.blakadder.com/assets/device_images/tuya_nightlight_plug.webp" },
  "Tuya|Tuya 20A Switch": { r: "https://templates.blakadder.com/tuya_DS-161.html", i: "https://templates.blakadder.com/assets/device_images/tuya_DS-161.webp" },
  "Tuya|Tuya 3 Gang": { r: "https://templates.blakadder.com/tuya_3_gang.html", i: "https://templates.blakadder.com/assets/device_images/tuya_3_gang.webp" },
  "Tuya|Tuya 4 Gang": { r: "https://templates.blakadder.com/Z6HS-L4D.html", i: "https://templates.blakadder.com/assets/device_images/Z6HS-L4D.webp" },
  "Tuya|Tuya 9W High CRI CCT Rotating Spot": { r: "https://templates.blakadder.com/smatrul_SD002.html", i: "https://templates.blakadder.com/assets/device_images/tuya_SD002.webp" },
  "Tuya|Tuya 9W High CRI CCT Spot": { r: "https://templates.blakadder.com/smatrul_SD001-9W.html", i: "https://templates.blakadder.com/assets/device_images/tuya_SD001-9W.webp" },
  "Tuya|Tuya Air Detector 6 in 1": { r: "https://templates.blakadder.com/tuya_DCR-KQG.html", i: "https://templates.blakadder.com/assets/device_images/tuya_DCR-KQG.webp" },
  "Tuya|Tuya Alarm PIR Motion Sensor CT61W": { r: "https://templates.blakadder.com/CT61W.html", i: "https://templates.blakadder.com/assets/device_images/CT61W.webp" },
  "Tuya|Tuya Gas Valve": { r: "https://templates.blakadder.com/tuya_RQF-1T.html", i: "https://templates.blakadder.com/assets/device_images/tuya_RQF-1T.webp" },
  "Tuya|Tuya Gas/Water Valve": { r: "https://templates.blakadder.com/FM101.html", i: "https://templates.blakadder.com/assets/device_images/FM101.webp" },
  "Tuya|Tuya Illuminance Sensor": { r: "https://templates.blakadder.com/lightsensor_XFY-CGQ-GZ.html", i: "https://templates.blakadder.com/assets/device_images/lightsensor_XFY-CGQ-GZ.webp" },
  "Tuya|Tuya Mini Switch": { r: "https://templates.blakadder.com/MK-601.html", i: "https://templates.blakadder.com/assets/device_images/MK-601.webp" },
  "Tuya|Tuya PM Box": { r: "https://templates.blakadder.com/tuya_pm_box.html", i: "https://templates.blakadder.com/assets/device_images/tuya_pm_box.webp" },
  "Tuya|Tuya RGB+CCT 12-24V LED Controller": { r: "https://templates.blakadder.com/ZB001.html", i: "https://templates.blakadder.com/assets/device_images/ZB001.webp" },
  "Tuya|Tuya RGBCCT LED Controller": { r: "https://templates.blakadder.com/TY-6A-WiFi.html", i: "https://templates.blakadder.com/assets/device_images/TY-6A-WiFi.webp" },
  "Tuya|Tuya S08": { r: "https://templates.blakadder.com/S08.html", i: "https://templates.blakadder.com/assets/device_images/S08.webp" },
  "Tuya|Tuya Smart Remote": { r: "https://templates.blakadder.com/ZN281402.html", i: "https://templates.blakadder.com/assets/device_images/ZN281402.webp" },
  "Tuya|Tuya T1 2 Gang No Neutral": { r: "https://templates.blakadder.com/DS-1081WL_2.html", i: "https://templates.blakadder.com/assets/device_images/DS-1081WL_2.webp" },
  "Tuya|Tuya T1 3 Gang No Neutral": { r: "https://templates.blakadder.com/DS-1081WL_3.html", i: "https://templates.blakadder.com/assets/device_images/DS-1081WL_3.webp" },
  "Tuya|Tuya WB5 5 in 1 LED Controller": { r: "https://templates.blakadder.com/WB5.html", i: "https://templates.blakadder.com/assets/device_images/WB5.webp" },
  "Tuya|Tuya mmWave Presence Sensor": { r: "https://templates.blakadder.com/ZY-M100.html", i: "https://templates.blakadder.com/assets/device_images/ZY-M100.webp" },
  "eWeLink|EARU DIN Circuit Breaker 1P 63A eWeLink Version": { r: "https://templates.blakadder.com/earu_RDCBC-1P_ewelink.html", i: "https://templates.blakadder.com/assets/device_images/earu_RDCBC-1P_ewelink.webp" },
  "eWeLink|EARU DIN Circuit Breaker 2P 63/80A eWeLink White": { r: "https://templates.blakadder.com/earu_RDCBC-2P_ewelink.html", i: "https://templates.blakadder.com/assets/device_images/earu_RDCBC-2P_ewelink.webp" },
  "eWeLink|Eachen eWeLink ZbBridge Pro Ethernet": { r: "https://templates.blakadder.com/ewelink_ZB-GW03.html", i: "https://templates.blakadder.com/assets/device_images/ewelink_ZB-GW03.webp" },
  "eWeLink|eWeLink Candle Light 5W RGBCCT": { r: "https://templates.blakadder.com/ewelink_candle.html", i: "https://templates.blakadder.com/assets/device_images/ewelink_candle.webp" },
  "eWeLink|eWeLink EU 20A Plug AJW-02_8285": { r: "https://templates.blakadder.com/ewelink_AJW-02_8285.html", i: "https://templates.blakadder.com/assets/device_images/ewelink_AJW-02_8285.webp" },
  "eWeLink|eWeLink PSF-B04 5V 7-32V 4 Channel": { r: "https://templates.blakadder.com/ewelink_4CH.html", i: "https://templates.blakadder.com/assets/device_images/ewelink_4CH.webp" },
  "eWeLink|eWeLink RF No Neutral 3 Channel": { r: "https://templates.blakadder.com/ewelink_3CH.html", i: "https://templates.blakadder.com/assets/device_images/ewelink_3CH.webp" },
};
